import { Inter, Open_Sans } from "next/font/google";
import "../globals.css";
import "react-toastify/dist/ReactToastify.css";
const opensans = Open_Sans({ subsets: ["latin"] });

export const metadata = {
  title: "Login to your account",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={opensans.className}>
        <main className="min-h-[100vh] bg-slate-600 flex items-center">
          {children}
        </main>
      </body>
    </html>
  );
}
