"use client";
import { useState, useEffect } from "react";
import { Bar, Pie } from "react-chartjs-2";
import jsPDF from "jspdf";

import {
  Chart as ChartJS,
  CategoryScale,
  LinearScale,
  BarElement,
  Title,
  Tooltip,
  Legend,
  ArcElement,
} from "chart.js";
import { GetAllExpenses } from "@/utils/helper";
import { useSession } from "next-auth/react";
import ImprovedDatePicker from "../ImprovedDatePicker";
ChartJS.register(
  CategoryScale,
  LinearScale,
  BarElement,
  Title,
  Tooltip,
  Legend,
  ArcElement
);

export default function ExpenseReport() {
  const [expenseData, setExpenseData] = useState([]);
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState(null);
  const [startDate, setStartDate] = useState("");
  const [endDate, setEndDate] = useState("");
  const { data: session } = useSession();
  const username = session?.user?.name;
  const email = session?.user?.email;

  const generatePDF = () => {
    const doc = new jsPDF();
    let yOffset = 20;
    const pageWidth = doc.internal.pageSize.width;

    // Helper function for centered text
    const centeredText = (text, y) => {
      const textWidth =
        (doc.getStringUnitWidth(text) * doc.internal.getFontSize()) /
        doc.internal.scaleFactor;
      const textOffset = (pageWidth - textWidth) / 2;
      doc.text(text, textOffset, y);
    };

    // Add title
    doc.setFontSize(24);
    doc.setTextColor(44, 62, 80); // Dark blue
    centeredText("Expense Report", yOffset);
    yOffset += 10;

    // Add user info
    doc.setFontSize(12);
    doc.setTextColor(52, 73, 94); // Slightly lighter blue
    centeredText(`Generated by: ${username}`, yOffset);
    yOffset += 7;
    centeredText(`Email: ${email}`, yOffset);
    yOffset += 8;

    doc.setFontSize(12);
    doc.setTextColor(52, 73, 90); // Forest Green
    centeredText(
      `Date Range: ${
        startDate !== "" || endDate !== ""
          ? `${startDate} to ${endDate}`
          : "All Data"
      }`,
      yOffset
    );
    yOffset += 15;

    // Add summary
    doc.setFillColor(236, 240, 241); // Light gray background
    doc.rect(20, yOffset, pageWidth - 40, 30, "F");
    yOffset += 5;

    doc.setFontSize(14);
    doc.setTextColor(44, 62, 80); // Dark blue
    doc.text(
      `Total Expenses: BDT ${totalExpense.toFixed(2)}`,
      25,
      yOffset + 10
    );
    doc.text(
      `Highest Expense Category: ${highestExpenseCategory}`,
      25,
      yOffset + 20
    );
    yOffset += 40;

    // Add expense details
    doc.setFontSize(16);
    doc.setTextColor(44, 62, 80); // Dark blue
    doc.text("Expense Details:", 20, yOffset);
    yOffset += 10;

    // Table header
    const tableHeaders = ["No.", "Title", "Amount (BDT)", "Category"];
    const columnWidths = [20, 63, 35, 55];

    doc.setFillColor(52, 152, 219); // Light blue header
    doc.rect(20, yOffset, pageWidth - 40, 10, "F");
    doc.setTextColor(255, 255, 255); // White text
    doc.setFontSize(12);

    let xOffset = 20;
    tableHeaders.forEach((header, index) => {
      doc.text(header, xOffset + 2, yOffset + 7);
      xOffset += columnWidths[index];
    });
    yOffset += 15;

    // Table rows
    doc.setTextColor(44, 62, 80); // Dark blue text
    expenseData.forEach((expense, index) => {
      if (yOffset > 270) {
        doc.addPage();
        yOffset = 20;
      }

      xOffset = 20;
      if (index % 2 === 0) {
        doc.setFillColor(236, 240, 241); // Light gray for even rows
        doc.rect(20, yOffset - 5, pageWidth - 40, 10, "F");
      }

      doc.text((index + 1).toString(), xOffset + 2, yOffset);
      xOffset += columnWidths[0];
      doc.text(expense.title, xOffset + 2, yOffset);
      xOffset += columnWidths[1];
      doc.text(expense.amount.toFixed(2), xOffset + 2, yOffset);
      xOffset += columnWidths[2];
      doc.text(expense.category, xOffset + 2, yOffset);

      yOffset += 10;
    });

    // Add footer
    const pageCount = doc.internal.getNumberOfPages();
    for (let i = 1; i <= pageCount; i++) {
      doc.setPage(i);
      doc.setFontSize(10);
      doc.setTextColor(127, 140, 141); // Gray text
      doc.text(
        `Page ${i} of ${pageCount}`,
        pageWidth - 40,
        doc.internal.pageSize.height - 10
      );
    }

    // Save the PDF
    doc.save(`expense_report_${username}.pdf`);
  };

  useEffect(() => {
    const fetchExpenseData = async () => {
      try {
        const res = await fetch(
          `/api/reports/expenses?startDate=${startDate}&endDate=${endDate}`
        );
        const { expenses } = await res.json();
        setExpenseData(expenses);
      } catch (err) {
        setError("Failed to fetch expense data.");
        console.error("Error fetching expense data:", err);
      } finally {
        setLoading(false);
      }
    };

    fetchExpenseData();
  }, [startDate, endDate]);

  if (loading) {
    return (
      <div className="container mx-auto flex justify-center items-center h-64 bg-slate-100 rounded shadow-md">
        <div className="loader ease-linear rounded-full border-8 border-t-8 border-gray-200 h-16 w-16"></div>
      </div>
    );
  }

  if (error) {
    return (
      <div className="container mx-auto p-4 mb-6 bg-white rounded shadow-md text-red-500">
        Error: {error}
      </div>
    );
  }

  if (expenseData.length === 0) {
    return (
      <div className="p-4 mb-6 bg-white rounded shadow-md">
        No expense data available
      </div>
    );
  }

  // Prepare data for charts
  const categories = [
    ...new Set(expenseData.map((expense) => expense.category)),
  ];
  const categoryTotals = categories.map((category) =>
    expenseData
      .filter((expense) => expense.category === category)
      .reduce((sum, expense) => sum + expense.amount, 0)
  );

  const totalExpense = categoryTotals.reduce((sum, total) => sum + total, 0);
  const highestExpenseCategory =
    categories[categoryTotals.indexOf(Math.max(...categoryTotals))];

  const barData = {
    labels: categories,
    datasets: [
      {
        label: "Expenses",
        data: categoryTotals,
        backgroundColor: [
          "#FF6384", // Red
          "#36A2EB", // Blue
          "#FFCE56", // Yellow
          "#4BC0C0", // Teal
          "#9966FF", // Purple
          "#FF9F40", // Orange
          "#E7E9AC", // Light Green
          "#C9CBCF", // Gray
          "#FF6347", // Tomato
          "#40E0D0", // Turquoise
          "#FFD700", // Gold
          "#ADFF2F", // Green Yellow
          "#FF69B4", // Hot Pink
          "#7B68EE", // Medium Slate Blue
          "#FF4500", // Orange Red
          "#DA70D6", // Orchid
          "#C71585", // Medium Violet Red
          "#00FA9A", // Medium Spring Green
          "#FF1493", // Deep Pink
          "#1E90FF", // Dodger Blue
          "#32CD32", // Lime Green
          "#8A2BE2", // Blue Violet
          "#A9A9A9", // Dark Gray
        ],
      },
    ],
  };

  const pieData = {
    labels: categories,
    datasets: [
      {
        label: "Expenses",
        data: categoryTotals,
        backgroundColor: [
          "#FF6384", // Red
          "#36A2EB", // Blue
          "#FFCE56", // Yellow
          "#4BC0C0", // Teal
          "#9966FF", // Purple
          "#FF9F40", // Orange
          "#E7E9AC", // Light Green
          "#C9CBCF", // Gray
          "#FF6347", // Tomato
          "#40E0D0", // Turquoise
          "#FFD700", // Gold
          "#ADFF2F", // Green Yellow
          "#FF69B4", // Hot Pink
          "#7B68EE", // Medium Slate Blue
          "#FF4500", // Orange Red
          "#DA70D6", // Orchid
          "#C71585", // Medium Violet Red
          "#00FA9A", // Medium Spring Green
          "#FF1493", // Deep Pink
          "#1E90FF", // Dodger Blue
          "#32CD32", // Lime Green
          "#8A2BE2", // Blue Violet
          "#A9A9A9", // Dark Gray
        ],
      },
    ],
  };

  return (
    <div className="p-6 container mx-auto relative mb-6 bg-slate-100 rounded-lg shadow-md">
      <h2 className="text-3xl font-bold text-gray-700 mb-12 text-center">
        Expense Report
      </h2>
      <div className="hidden mb-10 md:flex flex-row justify-between items-center">
        <div className=" w-full lg:w-2/3">
          <ImprovedDatePicker
            startDate={startDate}
            endDate={endDate}
            setStartDate={setStartDate}
            setEndDate={setEndDate}
          />
        </div>
        <div className="hidden md:flex h-12 mt-8">
          <button
            onClick={generatePDF}
            className="px-4 py-2 bg-blue-500 text-white rounded hover:bg-blue-600 transition-colors"
          >
            Download Report
          </button>
        </div>
      </div>
      {/* Summary Section */}
      <div className="mb-10">
        <h3 className="text-xl font-semibold text-gray-600 mb-2">Summary</h3>
        <div className="grid grid-cols-1 md:grid-cols-3 gap-4">
          <div className="p-4 bg-gray-100 rounded shadow">
            <p className="text-lg font-medium">Date Range</p>
            <p className="text-xl font-bold text-green-600">
              {startDate}
              {startDate === "" ? (
                <span>Select a date range</span>
              ) : (
                <span> to</span>
              )}{" "}
              {endDate}
            </p>
          </div>
          <div className="p-4 bg-gray-100 rounded shadow">
            <p className="text-lg font-medium">Total Expenses</p>
            <p className="text-2xl font-bold text-red-600">
              BDT {totalExpense.toFixed(2)}
            </p>
          </div>
          <div className="p-4 bg-gray-100 rounded shadow">
            <p className="text-lg font-medium">Highest Expense Category</p>
            <p className="text-2xl font-bold text-red-600">
              {highestExpenseCategory}
            </p>
          </div>
        </div>
      </div>

      {/* Charts Section */}
      <div className="grid grid-cols-1 md:grid-cols-2 gap-8">
        <div>
          <h3 className="text-lg font-semibold text-gray-600 mb-4">
            Expense by Category
          </h3>
          <div className="relative h-64">
            <Bar
              data={barData}
              options={{
                responsive: true,
                maintainAspectRatio: false,
                plugins: {
                  legend: { position: "top" },
                  tooltip: {
                    callbacks: {
                      label: (tooltipItem) => `Amount: ${tooltipItem.raw} Tk`,
                    },
                  },
                },
              }}
            />
          </div>
        </div>
        <div>
          <h3 className="text-lg font-semibold text-gray-600 mb-4">
            Expense by Category (Pie Chart)
          </h3>
          <div className="relative h-64">
            <Pie
              data={pieData}
              options={{
                responsive: true,
                maintainAspectRatio: false,
                plugins: {
                  legend: { position: "top" },
                  tooltip: {
                    callbacks: {
                      label: (tooltipItem) => `Amount: ${tooltipItem.raw} Tk`,
                    },
                  },
                },
              }}
            />
          </div>
        </div>
      </div>
      <div className="md:hidden mt-8">
        <button
          onClick={generatePDF}
          className="absolute right-0 left-0 bottom-0 px-4 py-2 bg-blue-500 text-white rounded hover:bg-blue-600 transition-colors"
        >
          Download Report
        </button>
      </div>
    </div>
  );
}
