import { Inter, Open_Sans } from "next/font/google";
import "../globals.css";
import Sidebar from "@/components/Sidebar";
import Navbar from "@/components/Navbar";
import AddFinanceButton from "@/components/AddFinanceButton";
import { ToastContainer } from "react-toastify";
import "react-toastify/dist/ReactToastify.css";
import AuthProvider from "@/utils/AuthProvider";
import { BudgetProvider } from "@/utils/BudgetContext";
const opensans = Open_Sans({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={opensans.className}>
        <AuthProvider>
          <BudgetProvider>
            <div className="flex min-h-screen bg-gray-900">
              {/* <Sidebar /> */}
              <div className="flex-1">
                <Navbar />
                <main className="p-6 mt-10 ">
                  {children}
                  <div className="container mx-auto">
                    <AddFinanceButton />
                  </div>
                  <ToastContainer />
                </main>
              </div>
            </div>
          </BudgetProvider>
        </AuthProvider>
      </body>
    </html>
  );
}
