import { Inter, Open_Sans } from "next/font/google";
import "./globals.css";
import Sidebar from "@/components/Sidebar";
import Navbar from "@/components/Navbar";
import AddFinanceButton from "@/components/AddFinanceButton";
const inter = Inter({ subsets: ["latin"] });
const opensans = Open_Sans({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={opensans.className}>
        <div className="flex min-h-screen">
          {/* <Sidebar /> */}
          <div className="flex-1">
            <Navbar />
            <main className="p-6 mt-10">
              {children} <AddFinanceButton />{" "}
            </main>
          </div>
        </div>
      </body>
    </html>
  );
}
